M48
; DRILL file {KiCad 6.0.2+dfsg-1} date wo 19 apr 2023 23:44:22 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-19T23:44:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X83.843Y-59.979
X91.079Y-59.978
T2
X152.233Y-20.908
X152.233Y-30.908
T3
X75.651Y-24.085
X75.651Y-32.285
T4
X76.708Y-18.288
X77.102Y-62.61
X138.802Y-18.31
X153.802Y-63.41
T0
M30
