name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: davidv27/picopico-builder:0.0.5
      volumes:
        - "${{ github.workspace }}:/src"
      env:
        GIT_SSL_NO_VERIFY: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build 3DS
        run: mkdir build-3ds && cd build-3ds && cmake .. -DBACKEND=THREEDS && make -j

      - name: Build android
        run: mkdir build-android && cd build-android && cmake .. -DANDROIDSDK=/android_sdk -DBACKEND=ANDROID && make -j

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 3DS Cart
          path: build-3ds/3ds_pico.3dsx

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Android APP
          path: build-android/cnfgtest.apk
